name: "dev-release"

on:
  push:
    branches:
      - "dev"

jobs:
  pre-release:
    name: "Dev Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
    - name: "Build & test"
      run: |
        echo "done!"
    # - uses: actions/checkout@v2
    # - name: Set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8
    # - name: Run tests
    #   run: sbt clean test

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.ACCESS_TOKEN }}"
        automatic_release_tag: "dev-${{ github.GITHUB_SHA }}"
        prerelease: true
        title: "Development Build"
        files: |
          LICENSE.txt
          *.jar